version: 2.1

orbs:
  hmpps: ministryofjustice/hmpps@7.3.1

parameters:
  alerts-slack-channel:
    type: string
    default: approved-premises-team-events
  releases-slack-channel:
    type: string
    default: approved-premises-team-events

jobs:
  trigger-ui-tests:
    docker: 
      - image: cimg/base:stable
    resource_class: small
    steps:
      - run:
          name: "Approved Premises UI test"
          command: | 
              curl --request POST \
                --url https://circleci.com/api/v2/project/github/ministryofjustice/hmpps-approved-premises-ui/pipeline \
                --header "Circle-Token: $CIRCLECI_PIPELINE_TOKEN" \
                --header "content-type: application/json" \
                --data '{"branch":"main"}'
      - run:
          name: "Temporary Accommodation UI test"
          command: | 
              curl --request POST \
                --url https://circleci.com/api/v2/project/github/ministryofjustice/hmpps-temporary-accommodation-ui/pipeline \
                --header "Circle-Token: $CIRCLECI_PIPELINE_TOKEN" \
                --header "content-type: application/json" \
                --data '{"branch":"main"}'

workflows:
  version: 2
  build-test-and-deploy:
    jobs:
      - hmpps/helm_lint:
          name: helm_lint
      - hmpps/build_multiplatform_docker:
          name: build_docker
          filters:
            branches:
              only:
                - main
      - hmpps/deploy_env:
          name: deploy_dev
          env: "dev"
          context: hmpps-common-vars
          filters:
            branches:
              only:
                - main
          requires:
            - build_docker
            - helm_lint
      - request-test-approval:
          type: approval
          requires:
            - deploy_dev
      - hmpps/deploy_env:
          name: deploy_test
          env: "test"
          context:
            - hmpps-common-vars
            - hmpps-approved-premises-api-stage
          requires:
            - request-test-approval
      - request-preprod-approval:
          type: approval
          requires:
            - deploy_dev
      - hmpps/deploy_env:
          name: deploy_preprod
          env: "preprod"
          context:
            - hmpps-common-vars
            - hmpps-approved-premises-api-preprod
          requires:
            - request-preprod-approval
      - request-prod-approval:
          type: approval
          requires:
            - deploy_preprod
      - hmpps/deploy_env:
          name: deploy_prod
          env: "prod"
          slack_notification: true
          slack_channel_name: << pipeline.parameters.releases-slack-channel >>
          context:
            - hmpps-common-vars
            - hmpps-approved-premises-api-prod
          requires:
            - request-prod-approval
      - trigger-ui-tests:
          requires:
            - deploy_dev

  security:
    triggers:
      - schedule:
          cron: "11 5 * * 1-5"
          filters:
            branches:
              only:
                - main
    jobs:
      - hmpps/gradle_owasp_dependency_check:
          slack_channel: << pipeline.parameters.alerts-slack-channel >>
          context:
            - hmpps-common-vars
      - hmpps/trivy_latest_scan:
          slack_channel: << pipeline.parameters.alerts-slack-channel >>
          context:
            - hmpps-common-vars
      - hmpps/veracode_pipeline_scan:
          slack_channel: << pipeline.parameters.alerts-slack-channel >>
          context:
            - veracode-credentials
            - hmpps-common-vars
  security-weekly:
    triggers:
      - schedule:
          cron: "0 5 * * 1"
          filters:
            branches:
              only:
                - main
    jobs:
      - hmpps/veracode_policy_scan:
          slack_channel: << pipeline.parameters.alerts-slack-channel >>
          context:
            - veracode-credentials
            - hmpps-common-vars
