openapi: 3.0.1
info:
  title: 'Community Accommodation Services: Approved Premises (CAS1)'
  version: 1.0.0
servers:
  - url: /cas1
paths:
  /premises/{premisesId}/lost-beds:
    post:
      tags:
        - lost beds
      summary: Posts a lost bed to a specified approved premises
      parameters:
        - name: premisesId
          in: path
          description: ID of the premises the lost bed is related to
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        description: details of the lost bed
        content:
          'application/json':
            schema:
              $ref: '_shared.yml#/components/schemas/NewLostBed'
        required: true
      responses:
        200:
          description: successful operation
          content:
            'application/json':
              schema:
                $ref: '_shared.yml#/components/schemas/LostBed'
        400:
          description: invalid params
          content:
            'application/problem+json':
              schema:
                $ref: '_shared.yml#/components/schemas/ValidationError'
        401:
          $ref: '_shared.yml#/components/responses/401Response'
        403:
          $ref: '_shared.yml#/components/responses/403Response'
        404:
          description: invalid premises ID or booking ID
          content:
            'application/json':
              schema:
                $ref: '_shared.yml#/components/schemas/Problem'
        500:
          $ref: '_shared.yml#/components/responses/500Response'
      x-codegen-request-body-name: body
    get:
      tags:
        - lost beds
      summary: Lists all Lost Beds entries for the Premises
      parameters:
        - name: premisesId
          in: path
          description: ID of the premises to show lost beds for
          required: true
          schema:
            type: string
            format: uuid
      responses:
        200:
          description: successful operation
          content:
            'application/json':
              schema:
                type: array
                items:
                  $ref: '_shared.yml#/components/schemas/LostBed'
        401:
          $ref: '_shared.yml#/components/responses/401Response'
        403:
          $ref: '_shared.yml#/components/responses/403Response'
        500:
          $ref: '_shared.yml#/components/responses/500Response'
  /premises/{premisesId}/lost-beds/{lostBedId}:
    get:
      tags:
        - lost beds
      summary: Returns a specific lost bed for a premises
      parameters:
        - name: premisesId
          in: path
          description: ID of the premises the lost bed is related to
          required: true
          schema:
            type: string
            format: uuid
        - name: lostBedId
          in: path
          description: ID of the lost bed
          required: true
          schema:
            type: string
            format: uuid
      responses:
        200:
          description: successful operation
          content:
            'application/json':
              schema:
                $ref: '_shared.yml#/components/schemas/LostBed'
        401:
          $ref: '_shared.yml#/components/responses/401Response'
        403:
          $ref: '_shared.yml#/components/responses/403Response'
        404:
          description: invalid premises or lost bed ID
          content:
            'application/json':
              schema:
                $ref: '_shared.yml#/components/schemas/Problem'
        500:
          $ref: '_shared.yml#/components/responses/500Response'
    put:
      tags:
        - lost beds
      summary: Updates a lost bed for a premises
      parameters:
        - name: premisesId
          in: path
          description: ID of the premises the lost bed is related to
          required: true
          schema:
            type: string
            format: uuid
        - name: lostBedId
          in: path
          description: ID of the lost bed
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        description: details of the lost bed
        content:
          'application/json':
            schema:
              $ref: '_shared.yml#/components/schemas/UpdateLostBed'
        required: true
      responses:
        200:
          description: successful operation
          content:
            'application/json':
              schema:
                $ref: '_shared.yml#/components/schemas/LostBed'
        400:
          description: invalid params
          content:
            'application/problem+json':
              schema:
                $ref: '_shared.yml#/components/schemas/ValidationError'
        401:
          $ref: '_shared.yml#/components/responses/401Response'
        403:
          $ref: '_shared.yml#/components/responses/403Response'
        404:
          description: invalid premises ID or booking ID
          content:
            'application/json':
              schema:
                $ref: '_shared.yml#/components/schemas/Problem'
        500:
          $ref: '_shared.yml#/components/responses/500Response'
      x-codegen-request-body-name: body
  /premises/{premisesId}/lost-beds/{lostBedId}/cancellations:
    post:
      tags:
        - lost beds
      summary: Posts a cancellation to a specified lost bed
      parameters:
        - name: premisesId
          in: path
          description: ID of the premises the cancellation is related to
          required: true
          schema:
            type: string
            format: uuid
        - name: lostBedId
          in: path
          description: ID of the lost bed
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        description: details of the cancellation
        content:
          'application/json':
            schema:
              $ref: '_shared.yml#/components/schemas/NewLostBedCancellation'
        required: true
      responses:
        200:
          description: successful operation
          content:
            'application/json':
              schema:
                $ref: '_shared.yml#/components/schemas/LostBedCancellation'
        400:
          description: invalid params
          content:
            'application/problem+json':
              schema:
                $ref: '_shared.yml#/components/schemas/ValidationError'
        401:
          $ref: '_shared.yml#/components/responses/401Response'
        403:
          $ref: '_shared.yml#/components/responses/403Response'
        404:
          description: invalid premises ID or lost bed ID
          content:
            'application/json':
              schema:
                $ref: '_shared.yml#/components/schemas/Problem'
        500:
          $ref: '_shared.yml#/components/responses/500Response'
      x-codegen-request-body-name: body
  /premises/{premisesId}/out-of-service-beds:
    post:
      tags:
        - out-of-service beds
      summary: Posts an out-of-service bed to a specified approved premises
      parameters:
        - name: premisesId
          in: path
          description: ID of the premises the out-of-service bed is related to
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        description: details of the out-of-service bed
        content:
          'application/json':
            schema:
              $ref: '_shared.yml#/components/schemas/NewCas1OutOfServiceBed'
        required: true
      responses:
        200:
          description: successful operation
          content:
            'application/json':
              schema:
                $ref: '_shared.yml#/components/schemas/Cas1OutOfServiceBed'
        400:
          description: invalid params
          content:
            'application/problem+json':
              schema:
                $ref: '_shared.yml#/components/schemas/ValidationError'
        401:
          $ref: '_shared.yml#/components/responses/401Response'
        403:
          $ref: '_shared.yml#/components/responses/403Response'
        404:
          description: invalid premises ID or booking ID
          content:
            'application/json':
              schema:
                $ref: '_shared.yml#/components/schemas/Problem'
        500:
          $ref: '_shared.yml#/components/responses/500Response'
      x-codegen-request-body-name: body
    get:
      tags:
        - out-of-service beds
      summary: Lists all Out-Of-Service Beds entries for the Premises
      parameters:
        - name: premisesId
          in: path
          description: ID of the premises to show out-of-service beds for
          required: true
          schema:
            type: string
            format: uuid
      responses:
        200:
          description: successful operation
          content:
            'application/json':
              schema:
                type: array
                items:
                  $ref: '_shared.yml#/components/schemas/Cas1OutOfServiceBed'
        401:
          $ref: '_shared.yml#/components/responses/401Response'
        403:
          $ref: '_shared.yml#/components/responses/403Response'
        500:
          $ref: '_shared.yml#/components/responses/500Response'
  /premises/{premisesId}/out-of-service-beds/{outOfServiceBedId}:
    get:
      tags:
        - out-of-service beds
      summary: Returns a specific out-of-service bed for a premises
      parameters:
        - name: premisesId
          in: path
          description: ID of the premises the out-of-service bed is related to
          required: true
          schema:
            type: string
            format: uuid
        - name: outOfServiceBedId
          in: path
          description: ID of the out-of-service bed
          required: true
          schema:
            type: string
            format: uuid
      responses:
        200:
          description: successful operation
          content:
            'application/json':
              schema:
                $ref: '_shared.yml#/components/schemas/Cas1OutOfServiceBed'
        401:
          $ref: '_shared.yml#/components/responses/401Response'
        403:
          $ref: '_shared.yml#/components/responses/403Response'
        404:
          description: invalid premises or out-of-service bed ID
          content:
            'application/json':
              schema:
                $ref: '_shared.yml#/components/schemas/Problem'
        500:
          $ref: '_shared.yml#/components/responses/500Response'
    put:
      tags:
        - out-of-service beds
      summary: Updates an out-of-service bed for a premises
      parameters:
        - name: premisesId
          in: path
          description: ID of the premises the out-of-service bed is related to
          required: true
          schema:
            type: string
            format: uuid
        - name: outOfServiceBedId
          in: path
          description: ID of the out-of-service bed
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        description: details of the out-of-service bed
        content:
          'application/json':
            schema:
              $ref: '_shared.yml#/components/schemas/UpdateCas1OutOfServiceBed'
        required: true
      responses:
        200:
          description: successful operation
          content:
            'application/json':
              schema:
                $ref: '_shared.yml#/components/schemas/Cas1OutOfServiceBed'
        400:
          description: invalid params
          content:
            'application/problem+json':
              schema:
                $ref: '_shared.yml#/components/schemas/ValidationError'
        401:
          $ref: '_shared.yml#/components/responses/401Response'
        403:
          $ref: '_shared.yml#/components/responses/403Response'
        404:
          description: invalid premises ID or booking ID
          content:
            'application/json':
              schema:
                $ref: '_shared.yml#/components/schemas/Problem'
        500:
          $ref: '_shared.yml#/components/responses/500Response'
      x-codegen-request-body-name: body
  /premises/{premisesId}/out-of-service-beds/{outOfServiceBedId}/cancellations:
    post:
      tags:
        - out-of-service beds
      summary: Posts a cancellation to a specified out-of-service bed
      parameters:
        - name: premisesId
          in: path
          description: ID of the premises the cancellation is related to
          required: true
          schema:
            type: string
            format: uuid
        - name: outOfServiceBedId
          in: path
          description: ID of the out-of-service bed
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        description: details of the cancellation
        content:
          'application/json':
            schema:
              $ref: '_shared.yml#/components/schemas/NewCas1OutOfServiceBedCancellation'
        required: true
      responses:
        200:
          description: successful operation
          content:
            'application/json':
              schema:
                $ref: '_shared.yml#/components/schemas/Cas1OutOfServiceBedCancellation'
        400:
          description: invalid params
          content:
            'application/problem+json':
              schema:
                $ref: '_shared.yml#/components/schemas/ValidationError'
        401:
          $ref: '_shared.yml#/components/responses/401Response'
        403:
          $ref: '_shared.yml#/components/responses/403Response'
        404:
          description: invalid premises ID or out-of-service bed ID
          content:
            'application/json':
              schema:
                $ref: '_shared.yml#/components/schemas/Problem'
        500:
          $ref: '_shared.yml#/components/responses/500Response'
      x-codegen-request-body-name: body
