---
# Per environment values which override defaults in approved-premises-api/values.yaml

generic-service:
  replicaCount: 2

  ingress:
    host: approved-premises-api-dev.hmpps.service.justice.gov.uk
    tlsSecretName: hmpps-approved-premises-api-dev-cert

  env:
    SPRING_PROFILES_ACTIVE: dev
    APPLICATIONINSIGHTS_CONFIGURATION_FILE: applicationinsights.dev.json
    HMPPS_AUTH_URL: https://sign-in-dev.hmpps.service.justice.gov.uk/auth
    SERVICES_COMMUNITY-API_BASE-URL: https://community-api-secure.test.delius.probation.hmpps.dsd.io
    SERVICES_AP-DELIUS-CONTEXT-API_BASE-URL: https://approved-premises-and-delius.test.probation.service.justice.gov.uk
    SERVICES_ASSESS-RISKS-AND-NEEDS-API_BASE-URL: https://assess-risks-and-needs-dev.hmpps.service.justice.gov.uk
    SERVICES_HMPPS-TIER_BASE-URL: https://hmpps-tier-dev.hmpps.service.justice.gov.uk
    SERVICES_PRISONS-API_BASE-URL: https://api-dev.prison.service.justice.gov.uk
    SERVICES_CASE-NOTES_BASE-URL: https://dev.offender-case-notes.service.justice.gov.uk
    SPRING_FLYWAY_LOCATIONS: classpath:db/migration/all,classpath:db/migration/local+dev
    LOG-CLIENT-CREDENTIALS-JWT-INFO: true
    SENTRY_ENVIRONMENT: dev
    CACHES_STAFFMEMBERS_EXPIRY-SECONDS: 20

# CloudPlatform AlertManager receiver to route prometheus alerts to slack
# See https://user-guide.cloud-platform.service.justice.gov.uk/documentation/monitoring-an-app/how-to-create-alarms.html#creating-your-own-custom-alerts
generic-prometheus-alerts:
  alertSeverity: hmpps-approved-premises
