name: Generate UI Types

on:
  push:
    branches:
      - main
    paths:
      - 'src/main/resources/static/api.yml'

jobs:
  generate-ui:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger AP UI Type Generation Workflow
        if: ${{ github.ref == 'refs/heads/main' }}
        id: ap-trigger-ui-workflow
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.UI_REPO_ACCESS_TOKEN }}
          script: |
            await github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: 'hmpps-approved-premises-ui',
              workflow_id: 'generate-types.yml',
              ref: 'main'
            })
      - name: Trigger TA UI Type Generation Workflow
        if: ${{ github.ref == 'refs/heads/main' }}
        id: ta-trigger-ui-workflow
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.UI_REPO_ACCESS_TOKEN }}
          script: |
            await github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: 'hmpps-temporary-accommodation-ui',
              workflow_id: 'generate-types.yml',
              ref: 'main'
            })
